8412 hnetdttn impl
bcgov/moh-hni-esb pull request #90
Opened 2022-12-13 23:52 UTC by AnumehaSrivastava05

2022-12-29 19:11 UTC, weskubo-cgi requested changes

2023-01-06 22:54 UTC, weskubo-cgi commented on hnsecure/src/main/java/ca/bc/gov/hlth/hnsecure/routes/Route.java
> +		Predicate isHNETDTTN = exchangeProperty(Util.PROPERTY_RECEIVING_APP).isEqualToIgnoreCase(Util.HNETDTTN);
This hasn't been fixed.

2023-01-09 17:22 UTC, AnumehaSrivastava05 commented on hnsecure/src/main/java/ca/bc/gov/hlth/hnsecure/routes/Route.java
> +		Predicate isHNETDTTN = exchangeProperty(Util.PROPERTY_RECEIVING_APP).isEqualToIgnoreCase(Util.HNETDTTN);
Will fix

2023-01-09 17:45 UTC, weskubo-cgi approved these changes

2023-01-10 16:04 UTC, merged